### ISSUE TITLE
Use xsd:annotation to show hover and Go To Definition command

### ISSUE THREAD

**Issue by nlips** [rogalmic/vscode-xml-complete#11]
Three suggested features (inspired by Visual Studio XML editor) :

- Show a tooltip when the mouse is over an element name or attribute name. This tooltip show the documentation provided by the <xsd:annotation> element in the schema.
- Show the same documentation into the auto complete list
- Add a "Go to definition" in the context menu

**Comment by rogalmic** [comment]
Comments:
1. Tooltip -> seems nice, will check it.
2. Autocomplete should already show xsd:annotation info.
3. Go to definition -> does it mean showing xsd file? Seems like cool idea.

I will need to find some time for this :)

**Comment by rogalmic** [comment]
Build wit initial hover support ready for testing:
https://github.com/rogalmic/vscode-xml-complete/releases/tag/untagged-349ddfa84a2e34808da8

**Comment by rogalmic** [comment]
And test version for "go to definition":
https://github.com/rogalmic/vscode-xml-complete/releases/tag/untagged-8d43eeff125ef6d88650

**Comment by rogalmic** [comment]
Implemented...
