### ISSUE TITLE
I did tags, imports etc

### ISSUE THREAD

**Issue by AndersMad** [rogalmic/vscode-xml-complete#13]
I can see that you are working on the project so I want to let you know that I did completion on elements allowed only (also rewrote linter) supporting imports and multiple namespaces.

The thing is that it was a night-time pet project that evolved and its done in the web version (monaco) so not as an extension (a few minor differences) - so when (if) I'm done i better send you the whole thing for manual merge, extension tedt and validation etc. 

What do you think?

**Comment by rogalmic** [comment]
Sure, let me know once ready.  It is a pet project for me as well, so all help is welcome and delays expected.

I have just one goal here - to keep dependencies count to minimum, otherwise I would not even start this project since there are options that use java.

**Comment by AndersMad** [comment]
yes - I continued in your style.. btw what's the split on `. ` (dot) about on tag names in eg. the linter? that's the only thing i had out-comment afaik as dots are ok in names afaik.

I have to iron out some namespace issues on attributes and maybe add autocomplete on attributes enums.. I won't add sequence (order of elements) as it's rarely used/important imo.

**Comment by rogalmic** [comment]
Yeah, i started the project thinking about Wpf/Avalonia XAML and its features, ie:
```xml
<StackPanel>
  <StackPanel.Attribute>Something</StackPanel.Attribute>
</StackPanel>
```
or
```
<StackPanel Attribute="something">
```

I have not decided yet if it will stay...

**Comment by AndersMad** [comment]
ah okay - maybe as an option/flag on the mapping then. I also added `data-*` hard-coded as I'm using it for html stuff - could be an option too but hey 😏
