### ISSUE TITLE
Error fetching the schema file

### ISSUE THREAD

**Issue by prof7bit** [rogalmic/vscode-xml-complete#20]
See attached screenshot. It shows two errors although the xsd file exists at this location. Itfails to download the schema and autocomplete will not work. 

I have also attached a zip file containing the xml file causing the error.

![xml-complete-xsd-error](https://user-images.githubusercontent.com/1401589/65681243-c9450b80-e058-11e9-90a4-23559ff3baf2.png)

[IO-Link-01-DirectParamsDevice-20130515-IODD1.1.zip](https://github.com/rogalmic/vscode-xml-complete/files/3657315/IO-Link-01-DirectParamsDevice-20130515-IODD1.1.zip)

**Comment by rogalmic** [comment]
Seems this xsd link does not work for me:
```
$ curl "http://www.io-link.com/IODD/2010/10 IODD1.1.xsd"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://io-link.com/IODD/2010/10%20IODD1.1.xsd">here</a>.</p>
</body></html>
```

**Comment by prof7bit** [comment]
This is not a link, this is a tuple separated by whitespace.

It should probably implement some kind of heuristic to look for the schema file when the namespace lokks like a http URL.

**Comment by rogalmic** [comment]
OK, so the reason is obvious. Currently only absolute paths are supported.

**Comment by prof7bit** [comment]
Maybe categorize this as a feature request instead of a bug

**Comment by rogalmic** [comment]
Yes, and one bug needs fixing:
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256139(v%3Dvs.100)
vs
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms256100(v%3Dvs.100)

**Comment by rogalmic** [comment]
https://github.com/rogalmic/vscode-xml-complete/commit/2ab31350df3bd1c17bdc321db8fa08ecf850bd2c
