### ISSUE TITLE
How to set filename pattern or path glob mapping instead of "xmlns"

### ISSUE THREAD

**Issue by arkceajin** [rogalmic/vscode-xml-complete#22]
Using XML:
```
<AUTOSAR xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://autosar.org/schema/r4.0">
...
</AUTOSAR>
```

Setting:
```
    "xmlComplete.schemaMapping":
    [
        {
            "xmlns": "http://autosar.org/schema/r4.0",
            "xsdUri": "file:///C:/Users/s-jiu/Desktop/AP-R19-03/MethodologyAndManifests/AUTOSAR_MMOD_XMLSchema/AUTOSAR_00047.xsd",
            "strict": true // shows errors instead of tips
        }
    ]
```
But the complete function didn't work.

![image](https://user-images.githubusercontent.com/8335699/69836735-390c8800-128e-11ea-9657-046f85c1e4c7.png)

About the error maybe cause by the `xmlns` recognized as path not namespace, so search for the path `"http://autosar.org/schema/r4.0"`.

So I want know to any setting like xml path/filename glob map to xsd scheme.

**Comment by rogalmic** [comment]
Try lower case file name `file:///c:/Users/....`, as far a s I recall the download library had problem with uppercase drive names.

Also, when i try this:
```
<AUTOSAR   xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/autosaros/Standards/master/Adaptive%20Platform/19.03/MethodologyAndManifests/AUTOSAR_MMOD_XMLSchema/AUTOSAR_00047.xsd">
...
</AUTOSAR>
```
 I get autocomplete to work:

![image](https://user-images.githubusercontent.com/23117003/69854995-c948ce00-128a-11ea-878b-61c3b7627bae.png)

**Comment by rogalmic** [comment]
I noticed one issue with node names that contain dot or slash, so new version is available that hopefully will fix that.
