### ISSUE TITLE
Cannot find XSD schema file

### ISSUE THREAD

**Issue by bammi** [rogalmic/vscode-xml-complete#24]
In the attached example (.XML file) XML Complete always complains that it cannot find the XSD file. I have triple checked that the file exists at the specified location, and in fact if i open the sa,e XML file in Visual Studio it find the schema and does all the completions according to the schema correctly.
I tried both these syntaxes
xsi:noNamespaceSchemaLocation="file:///c:/Program Files/Memento/Memento Security/build.xsd"
and
xsi:noNamespaceSchemaLocation="c:\Program Files\Memento\Memento Security\build.xsd"

neither work (and they both work with Visual Studio).
![xsd_error](https://user-images.githubusercontent.com/76747/71776229-e6706b00-2fb3-11ea-8c58-861b7a436494.jpg)
![xsd_error2](https://user-images.githubusercontent.com/76747/71776242-32bbab00-2fb4-11ea-90e8-f576568f2852.jpg)
[](url)

**Comment by rogalmic** [comment]
Can you try to url encode the file location, ie. change spaces to `%20` ?

```
xsi:noNamespaceSchemaLocation="file:///c:/Program%20Files/Memento/Memento Security/build.xsd"
```

**Comment by bammi** [comment]
Thanks Michal,
using %20 for spaces got me a step further in that it now does not complain about not being able to find the XSD file, but now it gives me a spurious error on a line that does not exist in my XSD or the XML file. See attached screenshot

tanks
bammi

**Comment by rogalmic** [comment]
Cannot see any screenshot, please add directly from github page.

**Comment by bammi** [comment]
Per request screenshot added
![xsd_error_3](https://user-images.githubusercontent.com/76747/71826917-21ae8f00-30c5-11ea-8640-cece4f5ac6c7.jpeg)

**Comment by rogalmic** [comment]
Screenshot shows that `XMLSchema.xsd` was loaded. 'build.xsd' seems not found, please re-verify path if it does not contain any extra white space chars.

In case of problems please attach the xml and xsd files, so i can reproduce here.

**Comment by bammi** [comment]
Hi Michal the silly fit thing does not let me attach xml or xsd files only picture format files. Please indicate an alternate email address to send you the files. 

Cheers

**Comment by rogalmic** [comment]
You need to zip the files, then it will allow them AFAIK.

**Comment by bammi** [comment]
[files.zip](https://github.com/rogalmic/vscode-xml-complete/files/4045213/files.zip)

Files added in the ZIP, the XML file and the XSD file

**Comment by rogalmic** [comment]
I found the issue in formatting, which is used for nicer "Go to definition" support. 

The attribute values were not properly encoded, so :
```
<tag attr="&quot;" />
```
was changed to
```
<tag attr=""" />
```
which basically broke the xml.

Please update extension to v. 0.2.8 - it should fix this .
