### ISSUE TITLE
Setting for putting attributes on same line on format

### ISSUE THREAD

**Issue by mikkel-ol** [rogalmic/vscode-xml-complete#4]
Missing feature for enabling/disabling automatic same-line attributes on ~~save~~ format

**Comment by rogalmic** [comment]
Can you describe the request in more detail?

**Comment by mikkel-ol** [comment]
Yes of course.

I do apologize for the late reply, I somehow missed the notification of your response.

I updated the request to reflect what I meant - same line formatting (I forgot that not everyone has formatting on save..) 

To clarify I made a gif showing this.

<img src="https://imgur.com/W4J7y3K" alt="" width="400px">

**Comment by rogalmic** [comment]
I just released version 0.1.6 with formatting style configuration option, please take a look and test/comment.

```
        "xmlComplete.formattingStyle": {
          "description": "Defines if attributes should be single line or not.",
          "type": "string",
          "enum": [
            "singleLineAttributes",
            "multiLineAttributes",
            "fileSizeOptimized"
          ],
          "scope": "resource",
          "default": []
        },
```

**Comment by mikkel-ol** [comment]
Works perfectly.

Thank you!

**Comment by devel0** [comment]
An intermediate option would of help like a **preserveLineAttributes** where basically it not alter existing newlines but only indent ( space indentation and between attributes on the same line ).

example
```xml
    <Grid ColumnDefinitions="420,*">
    <!-- a comment sample -->
        <Grid Grid.Column="0" Background="#dedede"
            Margin="0,0,10,0">
```

currently formatted with `singleLineAttributes` generates follow:

```xml
<Grid ColumnDefinitions="420,*"><!-- a comment sample -->
        <Grid Grid.Column="0" Background="#dedede" Margin="0,0,10,0">
```

while I would like to have following with a `preserveLineAttributes`:

```xml
    <Grid ColumnDefinitions="420,*">
        <!-- a comment sample -->
        <Grid Grid.Column="0" Background="#dedede"
              Margin="0,0,10,0">
```

Another possibility is to add a `preserveMaxWidth` option to work with `preserveLineAttributes` case where if `0` then it fully preserve line attributes as shown upper but when >0 eg (120) it will break with newlines when lines exceed preferred width generating following in this case:

```xml
    <Grid ColumnDefinitions="420,*">
        <!-- a comment sample -->
        <Grid Grid.Column="0" Background="#dedede" Margin="0,0,10,0">
```
