### ISSUE TITLE
No completion of attributes

### ISSUE THREAD

**Issue by mrsimpson** [rogalmic/vscode-xml-complete#7]
IntelliSense does not pick up the attributes of an element specified like that

```xml
<xsd:complexType name="_ListItemType">
    <xsd:complexContent>
      <xsd:extension base="n0:_ItemType">
        <xsd:attribute name="icon" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>The icon belonging to this list item instance.
This can be a URI to an image or an icon font URI.</xsd:documentation>
          </xsd:annotation>
        </xsd:attribute>
```

I added the schema for your convenience (and test case production ;))
You may Try to add a `core:ListItem` and complete its properties.
[ZIP with schema and sample xml](https://github.com/rogalmic/vscode-xml-complete/files/3199953/Archiv.zip)

Cheers, 
Oliver

**Comment by rogalmic** [comment]
Should be fixed in next version...
