### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DarkAxi0m** [rogalmic/vscode-xml-complete#8]
Getting this error when using this xsd file.
https://raw.githubusercontent.com/propelorm/Propel/master/generator/resources/xsd/database.xsd

Not sure what else you need to assist.

```
<database name="default" defaultIdMethod="native"
           namespace="App\Database"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://raw.githubusercontent.com/propelorm/Propel/master/generator/resources/xsd/database.xsd"
        >
</database>
```

***VSCode details***
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by rogalmic** [comment]
Will be fixed in next release, sorry for delay.
